package ISSProject.network.rpcprotocol;


public enum RequestType {
    LOGIN_READER, LOGIN_LIBRARIAN, GET_ALL_BOOKS, SECURITY, LOGOUT_LIBRARIAN,
    LOGOUT_READER, LOAN_BOOK, RETURN_BOOK,REGISTER_READER, GET_ALL_BOOK_LOANS;
}
